apiVersion: v1
kind: Service
metadata:
  name: cigna-stock-service
  labels:
    app: cigna-stock-service
    component: cigna-stock-service
spec:
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30304
  selector:
    app: cigna-stock-service
    component: cigna-stock-service
  type: NodePort
