apiVersion: v1
kind: Service
metadata:
  name: cigna-api-gateway
  labels:
    app: cigna-api-gateway
    component: cigna-api-gateway
spec:
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30305
  selector:
    app: cigna-api-gateway
    component: cigna-api-gateway
  type: NodePort
