apiVersion: v1
kind: Service
metadata:
  name: cigna-eureka-service
  labels:
    app: cigna-eureka-service
    component: cigna-eureka-service
spec:
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30303
  selector:
    app: cigna-eureka-service
    component: cigna-eureka-service
  type: NodePort
